### ISSUE TITLE
Add Slack integrations (e.g. to track questions on platforms like Stackoverflow)

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk.github.io#163] opened 2017-01-26 10:57 UTC
In the past we have been working with Slack integrations (webhook based) to continuously track discussions (related to OpenWhisk) on other platforms, e.g. questions that arose on platforms like Stackoverflow.

That way we can make sure that we don't miss interesting discussions as well as people being generally interested and can make sure we are able to provide immediate help (by pointing to documentation, by inviting to our Slack channel to discuss...).

Thoughts?

**Comment by csantanapr** [comment] 2017-01-26 16:41
I think this a duplicate of #161 ?

**Comment by csantanapr** [comment] 2017-01-26 17:30
This is fix now

**Closed by csantanapr** 2017-01-26 17:30 UTC
